export const middleOfRo = [24.9668, 45.9432];

export const weatherCodeDescriptions = {
  0: "Clear sky",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Depositing rime fog",
  51: "Light drizzle",
  53: "Moderate drizzle",
  55: "Dense drizzle",
  56: "Light freezing drizzle",
  57: "Dense freezing drizzle",
  61: "Slight rain",
  63: "Moderate rain",
  65: "Heavy rain",
  66: "Light freezing rain",
  67: "Heavy freezing rain",
  71: "Slight snow fall",
  73: "Moderate snow fall",
  75: "Heavy snow fall",
  77: "Snow grains",
  80: "Slight rain showers",
  81: "Moderate rain showers",
  82: "Violent rain showers",
  85: "Slight snow showers",
  86: "Heavy snow showers",
  95: "Thunderstorm (slight)",
  96: "Thunderstorm (slight hail)",
  99: "Thunderstorm (severe hail)",
};

export const weatherIconsCodeDescriptionsURL = {
  0: "/images/weather/a_1_sunny.svg",
  1: "/images/weather/a_4_night.svg",
  2: "/images/weather/b_1_partly_cloudy.svg",
  3: "/images/weather/b_2_cloudy.svg",
  45: "/images/weather/d_4_fog.svg",
  48: "/images/weather/d_4_fog.svg",
  51: "/images/weather/c_1_rainy.svg",
  53: "/images/weather/c_1_rainy.svg",
  55: "/images/weather/c_1_rainy.svg",
  56: "/images/weather/d_3_sleet.svg",
  57: "/images/weather/d_3_sleet.svg",
  61: "/images/weather/c_1_rainy.svg",
  63: "/images/weather/c_1_rainy.svg",
  65: "/images/weather/c_2_heavy_rain.svg",
  66: "/images/weather/d_3_sleet.svg",
  67: "/images/weather/d_3_sleet.svg",
  71: "/images/weather/d_1_snow.svg",
  73: "/images/weather/d_2_heavy_snow.svg",
  75: "/images/weather/d_2_heavy_snow.svg",
  77: "/images/weather/g_3_snowflake.svg",
  80: "/images/weather/c_1_rainy.svg",
  81: "/images/weather/c_2_heavy_rain.svg",
  82: "/images/weather/c_2_heavy_rain.svg",
  85: "/images/weather/d_1_snow.svg",
  86: "/images/weather/d_2_heavy_snow.svg",
  95: "/images/weather/c_4_lightning.svg",
  96: "/images/weather/c_4_lightning.svg",
  99: "/images/weather/c_4_lightning.svg",
};

export const RANDOM_CITIES = [
  {
    name: "Paris",
    image: "/images/cities/Paris.webp",
    country: "France",
    lat: 48.8566,
    lon: 2.3522,
  },
  {
    name: "Berlin",
    image: "/images/cities/Berlin.webp",
    country: "Germany",
    lat: 52.52,
    lon: 13.405,
  },
  {
    name: "Madrid",
    image: "/images/cities/Madrid.webp",
    country: "Spain",
    lat: 40.4168,
    lon: -3.7038,
  },
  {
    name: "Rome",
    image: "/images/cities/Rome.webp",
    country: "Italy",
    lat: 41.9028,
    lon: 12.4964,
  },
  {
    name: "Vienna",
    image: "/images/cities/Vienna.webp",
    country: "Austria",
    lat: 48.2082,
    lon: 16.3738,
  },
  {
    name: "Amsterdam",
    image: "/images/cities/Amsterdam.webp",
    country: "Netherlands",
    lat: 52.3676,
    lon: 4.9041,
  },
  {
    name: "Prague",
    image: "/images/cities/Prague.webp",
    country: "Czech Republic",
    lat: 50.0755,
    lon: 14.4378,
  },
  {
    name: "Lisbon",
    image: "/images/cities/Lisbon.webp",
    country: "Portugal",
    lat: 38.7169,
    lon: -9.139,
  },
  {
    name: "Athens",
    image: "/images/cities/Athens.webp",
    country: "Greece",
    lat: 37.9838,
    lon: 23.7275,
  },
  {
    name: "Budapest",
    image: "/images/cities/Budapest.webp",
    country: "Hungary",
    lat: 47.4979,
    lon: 19.0402,
  },
  {
    name: "Dublin",
    image: "/images/cities/Dublin.webp",
    country: "Ireland",
    lat: 53.3498,
    lon: -6.2603,
  },
  {
    name: "Stockholm",
    image: "/images/cities/Stockholm.webp",
    country: "Sweden",
    lat: 59.3293,
    lon: 18.0686,
  },
  {
    name: "Bucuresti",
    image: "/images/cities/Bucuresti.webp",
    country: "Romania",
    lat: 44.4268,
    lon: 26.1025,
  },
  {
    name: "Helsinki",
    image: "/images/cities/Helsinki.webp",
    country: "Finland",
    lat: 60.1695,
    lon: 24.9354,
  },
  {
    name: "Warsaw",
    image: "/images/cities/Warsaw.webp",
    country: "Poland",
    lat: 52.2297,
    lon: 21.0122,
  },
  {
    name: "New York",
    image: "/images/cities/New%20York.webp",
    country: "USA",
    lat: 40.7128,
    lon: -74.006,
  },
  {
    name: "Kyoto",
    image: "/images/cities/Kyoto.webp",
    country: "Japan",
    lat: 35.0116,
    lon: 135.7681,
  },
  {
    name: "Beijing",
    image: "/images/cities/Beijing.webp",
    country: "China",
    lat: 39.9042,
    lon: 116.4074,
  },
  {
    name: "Mumbai",
    image: "/images/cities/Mumbai.webp",
    country: "India",
    lat: 19.076,
    lon: 72.8777,
  },
  {
    name: "Sydney",
    image: "/images/cities/Sydney.webp",
    country: "Australia",
    lat: -33.8688,
    lon: 151.2093,
  },
  {
    name: "Bangkok",
    image: "/images/cities/Bangkok.webp",
    country: "Thailand",
    lat: 13.7563,
    lon: 100.5018,
  },
  {
    name: "Buenos Aires",
    image: "/images/cities/Buenos%20Aires.webp",
    country: "Argentina",
    lat: -34.6037,
    lon: -58.3816,
  },
  {
    name: "Mexico City",
    image: "/images/cities/Mexico%20City.webp",
    country: "Mexico",
    lat: 19.4326,
    lon: -99.1332,
  },
  {
    name: "Cairo",
    image: "/images/cities/Cairo.webp",
    country: "Egypt",
    lat: 30.0444,
    lon: 31.2357,
  },
  {
    name: "Queenstown",
    image: "/images/cities/Queenstown.webp",
    country: "New Zealand",
    lat: -45.0312,
    lon: 168.6626,
  },
  {
    name: "Rio de Janeiro",
    image: "/images/cities/Rio%20de%20Janeiro.webp",
    country: "Brazil",
    lat: -22.9068,
    lon: -43.1729,
  },
  {
    name: "Seoul",
    image: "/images/cities/Seoul.webp",
    country: "South Korea",
    lat: 37.5665,
    lon: 126.978,
  },
  {
    name: "Toronto",
    image: "/images/cities/Toronto.webp",
    country: "Canada",
    lat: 43.6511,
    lon: -79.3839,
  },
  {
    name: "Singapore",
    image: "/images/cities/Singapore.webp",
    country: "Singapore",
    lat: 1.3521,
    lon: 103.8198,
  },
  {
    name: "Istanbul",
    image: "/images/cities/Istanbul.webp",
    country: "Turkey",
    lat: 41.0082,
    lon: 28.9784,
  },
  {
    name: "San Francisco",
    image: "/images/cities/San%20Francisco.webp",
    country: "USA",
    lat: 37.7749,
    lon: -122.4194,
  },
  {
    name: "Palermo",
    image: "/images/cities/Palermo.webp",
    country: "Italy",
    lat: 38.1157,
    lon: 13.3615,
  },
  {
    name: "Cape Town",
    image: "/images/cities/Cape%20Town.webp",
    country: "South Africa",
    lat: -33.9249,
    lon: 18.4241,
  },
  {
    name: "Cartagena",
    image: "/images/cities/Cartagena.webp",
    country: "Colombia",
    lat: 10.391,
    lon: -75.4794,
  },
  {
    name: "Tbilisi",
    image: "/images/cities/Tbilisi.webp",
    country: "Georgia",
    lat: 41.7151,
    lon: 44.8271,
  },
  {
    name: "Hoi An",
    image: "/images/cities/Hoi%20An.webp",
    country: "Vietnam",
    lat: 15.8801,
    lon: 108.338,
  },
  {
    name: "Dubrovnik",
    image: "/images/cities/Dubrovnik.webp",
    country: "Croatia",
    lat: 42.6507,
    lon: 18.0944,
  },
  {
    name: "Chefchaouen",
    image: "/images/cities/Chefchaouen.webp",
    country: "Morocco",
    lat: 35.1684,
    lon: -5.2636,
  },
  {
    name: "Taipei",
    image: "/images/cities/Taipei.webp",
    country: "Taiwan",
    lat: 25.033,
    lon: 121.5654,
  },
  {
    name: "Edinburgh",
    image: "/images/cities/Edinburgh.webp",
    country: "Scotland",
    lat: 55.9533,
    lon: -3.1883,
  },
  {
    name: "Lübeck",
    image: "/images/cities/L%C3%BCbeck.webp",
    country: "Germany",
    lat: 53.8655,
    lon: 10.6866,
  },
];

export const citiesTranslations = {
  Roma: "Rome",
  Praha: "Prague",
  München: "Munich",
  Zürich: "Zurich",
  Wien: "Vienna",
  Moskva: "Moscow",
  Lisboa: "Lisbon",
  København: "Copenhagen",
  Genève: "Geneva",
  Montréal: "Montreal",
  香港: "Hong Kong",
  北京: "Beijing",
  İstanbul: "Istanbul",
  القاهرة: "Cairo",
  新加坡: "Singapore",
  Buenos_Aires: "Buenos Aires",
  Santiago: "Santiago",
  São_Paulo: "São Paulo",
  Rio_de_Janeiro: "Rio de Janeiro",
  Guadalajara: "Guadalajara",
  Tokyo: "Tokyo",
  "New York": "New York City",
  "Los Angeles": "Los Angeles",
  "San Francisco": "San Francisco",
  Vancouver: "Vancouver",
  Sydney: "Sydney",
  Melbourne: "Melbourne",
  Milan: "Milan",
  Florence: "Florence",
  Madrid: "Madrid",
  Barcelona: "Barcelona",
  Paris: "Paris",
  Berlin: "Berlin",
  Rome: "Rome",
  Lima: "Lima",
  Cairo: "Cairo",
  Dhaka: "Dhaka",
  Lagos: "Lagos",
  Jakarta: "Jakarta",
  "Kuala Lumpur": "Kuala Lumpur",
  Seoul: "Seoul",
  Bangkok: "Bangkok",
  Hanoi: "Hanoi",
  "Cape Town": "Cape Town",
  Abuja: "Abuja",
  Kinshasa: "Kinshasa",
  "Addis Ababa": "Addis Ababa",
  Riyadh: "Riyadh",
  Manila: "Manila",
  Mumbai: "Mumbai",
  Kolkata: "Kolkata",
  Chennai: "Chennai",
  Hyderabad: "Hyderabad",
  Karachi: "Karachi",
  Lahore: "Lahore",
  Abidjan: "Abidjan",
  Douala: "Douala",
  Bamako: "Bamako",
  Accra: "Accra",
  "Dar es Salaam": "Dar es Salaam",
  Nairobi: "Nairobi",
  Algiers: "Algiers",
  Casablanca: "Casablanca",
  Montevideo: "Montevideo",
  Asunción: "Asunción",
  Quito: "Quito",
  "La Paz": "La Paz",
  Guayaquil: "Guayaquil",
  Tegucigalpa: "Tegucigalpa",
  Porto: "Porto",
  Tangier: "Tangier",
  Amman: "Amman",
  Yerevan: "Yerevan",
  Belgrade: "Belgrade",
  Warsaw: "Warsaw",
  Skopje: "Skopje",
  Sofia: "Sofia",
  Riga: "Riga",
  Tallinn: "Tallinn",
  Vilnius: "Vilnius",
  Zagreb: "Zagreb",
  Podgorica: "Podgorica",
  Sarajevo: "Sarajevo",
  Chisinau: "Chisinau",
  Bucharest: "Bucharest",
};
